---
engines:
 duplication:
   enabled: true
   exclude_paths:
     - "rstoolbox/bin/**"

exclude_paths:
  - "rstoolbox/tests/**"
  - "*/_version.py"
  - "versioneer.py"
  - "docs/**"
  - "sphinx-docs/**"

ratings:
  paths:
  - "**.py"