language: python
sudo: false
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
    os: linux
  - python: 3.5
    env: TOXENV=py35
    os: linux
  - python: 3.6
    env: TOXENV=py36
    os: linux
    after_success:
    - pwd
    - coveralls --data_file rstoolbox/tests/.coverage
    - python-codacy-coverage -r /tmp/cov-single.xml
    - bash <(curl -s https://codecov.io/bash) -Z -c -f /tmp/cov-single.xml
  - python: 3.7-dev
    env: TOXENV=py37
    os: linux
  - language: generic
    env: TOXENV=py27
    os: osx
    before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - "./miniconda.sh -b"
    - export PATH=/home/travis/miniconda2/bin:$PATH
    install:
    - /home/travis/miniconda2/bin/pip install --user tox-travis filelock codecov coverage
  - language: generic
    env: TOXENV=py36
    os: osx
    before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - "./miniconda.sh -b"
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm
    install:
    - conda install --yes python="3.6"
    - pip install --user tox-travis filelock codecov coverage
install:
- pip install tox
- if [[ $TOXENV == py36 ]]; then pip install pyyaml; fi
- if [[ $TOXENV == py36 ]]; then pip install coveralls; fi
- if [[ $TOXENV == py36 ]]; then pip install python-coveralls; fi
- if [[ $TOXENV == py36 ]]; then pip install codacy-coverage; fi
script:
- tox
deploy:
  provider: pypi
  user: jaume.bonet
  password:
    secure: Mc0ZDv9HKLAqFneaDU6xknIXnXY+aojY8VOyEEPu93fHABSxjvlkgcoggJHL8y5bag34caWoIGixFI4/slfuf+PUJNLIgm6AqgXpxKsU+gtXwQnEFwKLw65fLz0bCP5GPfPPeH811ZknD5AAw/e8tBYTI81EGh5TM/Y8OBtma4VgU8OrWbNX5gqxxHik/BAZZZh2bDRWq7syMBt5uUvw7rvx7ArDANWjXYcPwPoqVf5D+LY9P6lUBXDPes2lA7D2mk0ids2KojZLT4hI6U2+FwykRbdO7cMxrMYgVgs/oqpsr7tYkZeY16+56mJbt41V7/ofUNndJuaTPcjgLoaN2Ffi4DN7OvMC/CIOR2zyM/fU6SRBaHkT4KQuTMwUq2sw2BTUDMXSsYbn+fh8gc7Pq0EZ1OfDr8fdJRZL6LuwChjrinIh9gjSrZI21Wf1hSx/qwopG8WIl/CP8DXPzC/L2UKKlSBW5Squ5eHOzYRlWedeBxoky9nNCw8ryvzMiWGh36ZgCWT4QK0jWsYI28FIBf2sTyYqqTVimvpWwSVapgO2ZgKaH+tcn+ru2RKARHJBm1W7QVsOIsLop9GRsYwx7o1DsiLFM30r7AzbHpFWcTBzqQ33mdBi/7/bvhz/ExTOqbdEo7FFp1jzFW02DltHy8zBZp6s57bryDETTJT20bc=
  on:
    tags: true
    branch: master
    condition: $TRAVIS_PYTHON_VERSION == '3.6' && $TRAVIS_OS_NAME == 'linux'
